company id issue resolved while creating the companies
OWASP/BLT pull request #2089
Opened 2024-05-10 14:57 UTC by Uttkarsh-raj

While creating a company we are getting an issue of company_id is not unique which is because it is not getting set, this will give Integrity error in the code while making the requests.

Previously:

![Screenshot (99)](https://github.com/OWASP-BLT/BLT/assets/106571927/067a435e-ca32-4b13-9819-022b7f1f4cef)

Now:

![Screenshot (103)](https://github.com/OWASP-BLT/BLT/assets/106571927/924ec2c1-422c-49dd-a8af-421f947b90ff)

2024-05-10 18:42 UTC, AtmegaBuzz commented
LGTM!

2024-05-10 19:20 UTC, arkid15r reviewed
I think I should have mentioned this during the previous PR review: Django has a separate [UUID Field](https://docs.djangoproject.com/en/5.0/ref/models/fields/#uuidfield). The `company_id` should probably be `company_uuid` or just `uuid` if possible as it already is inside of `Company` context.

2024-05-10 19:20 UTC, arkid15r commented on website/models.py
> +        if not self.company_id:
Let's avoid the empty string case:
```suggestion
        if self.company_id is None:
```

2024-05-11 05:33 UTC, Uttkarsh-raj commented
> I think I should have mentioned this during the previous PR review: Django has a separate [UUID Field](https://docs.djangoproject.com/en/5.0/ref/models/fields/#uuidfield). The `company_id` should probably be `company_uuid` or just `uuid` if possible as it already is inside of `Company` context.

Or another way i thought of doing this was in the company_id field give the default value as uuid.uuid4 this also did the task but it could have generated some issue with respect to data already present in the database..

2024-05-11 05:40 UTC, DonnieBLT requested changes
Can we please use the auto id built in?

2024-05-11 05:41 UTC, DonnieBLT requested changes
We can remove company_id it's redundant

2024-05-11 05:58 UTC, Uttkarsh-raj commented
> We can remove company_id it's redundant

Ok will make this change...

2024-05-11 06:14 UTC, DonnieBLT requested changes

2024-05-11 06:25 UTC, DonnieBLT approved these changes

2024-05-11 06:25 UTC, Uttkarsh-raj commented on website/models.py
> +    # company_id = models.CharField(max_length=255, unique=True, editable=False)  # uuid
got changed when i pulled... should have checked carefully... thank you...

2024-05-11 14:39 UTC, DonnieBLT approved these changes

2024-05-11 14:39 UTC, merged