Make a Form for admins to accept Bids #2093
OWASP/BLT pull request #2104
Opened 2024-05-20 20:11 UTC by Sarthak5598

#2093

2024-05-20 21:03 UTC, arkid15r requested changes
Hi @Sarthak5598, 

could you look into the comments below when you get a chance:

2024-05-20 21:03 UTC, arkid15r commented on website/templates/bid_selection.html
> +            fetch(`/change-bid-status/`, {
Don't forget to change it here too

2024-05-20 21:03 UTC, arkid15r commented on website/views.py
> +def selectBid(request):
```suggestion
def select_bid(request):
```

2024-05-21 18:56 UTC, DonnieBLT requested changes

2024-05-21 19:54 UTC, Sarthak5598 commented on website/views.py
> +@csrf_exempt
**Done!**

2024-05-21 19:58 UTC, DonnieBLT approved these changes

2024-05-21 19:58 UTC, merged