team_overview page
OWASP/BLT pull request #3117
Opened 2024-12-17 06:48 UTC by krrish-sehgal

Summary
Fixes #3120

This PR introduces essential team management functionalities, including:

Creating a team
Leaving a team
Viewing team members
Kicking team members
Sending invitations to users
Deleting a team
Edge cases where user is in a team and is invited to another team 
admin leaves a team

The existing Company model has been enhanced by introducing a type field, which allows differentiation between:
team
individual
company

ref video: 

https://github.com/user-attachments/assets/a90a39ac-4a29-4c11-b1e2-d98e7331bef2

2024-12-17 06:56 UTC, krrish-sehgal commented
@DonnieBLT sir , Let me know if this team_overview dashboard aligns with you. 
if it does , I'll start working on getting the daily /weekly/monthly challenges PR, along with the leaderboard for individual and teams.

2024-12-17 13:32 UTC, DonnieBLT requested changes
Looks great! Let’s call it Teams instead

2024-12-17 13:34 UTC, krrish-sehgal commented
Sure sir , on it 👍

2024-12-17 14:26 UTC, DonnieBLT submitted a review, later dismissed

2024-12-18 10:36 UTC, DonnieBLT approved these changes

2024-12-18 10:36 UTC, merged